apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: net
  template:
    metadata:
      labels:
        app: net
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 9090          