apiVersion: v1
kind: Pod
metadata:
  name: static-pod
spec:

  restartPolicy: Always

  volumes:
  - name: shared-data
    emptyDir: {}

  initContainers:
  - name: init-debian-container
    image: debian

    volumeMounts:
    - name: shared-data
      mountPath: /work

    command: ["/bin/sh"]
    args: ["-c", "echo Hello from debian container > /work/index.html"]

  containers:

    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
      - name: shared-data
        mountPath: /usr/share/nginx/html

      readinessProbe:
        exec:
          command:
          - cat
          - usr/share/nginx/html/index.html
        initialDelaySeconds: 3
        periodSeconds: 3    

      livenessProbe:
        exec:
          command:
          - cat
          - usr/share/nginx/html/index.html
        initialDelaySeconds: 5
        periodSeconds: 5    
   

