apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # not using namespace since cluster roles are over all namespaces in the cluster
  name: pod-reader
rules:
- apiGroups: [""]  
  resources: ["pods"]
  verbs: ["get","watch","list"]